* fix bug in [game.cc -> bool game_t::load_mission_map(int level) ] causes wrong mission-random is used * fix error in is_valid_extension() if the road has zero length (may only occurs in MS Studio) * add tutorial function
Fix Error within appveyor: error C2864: 'game_init_box_t::game_mission' : only static const integral

fix error unsigned int (size_t) <-> signed int in demolish_building(). If a warehouse is being destroyed the gold is decreased but the function is called with an unsigned int.